image: docker:latest

stages:
    - build_nanomsg
    - build_python_nanomsg
    - build_python_msgpack
    - build_python_acurl
    - build_python_ujson
    - build_python_uvloop

before_script:
    - "docker login -u\"$DOCKER_USERNAME\" -p\"$DOCKER_PASSWORD\" $DOCKER_REPO"

build_nanomsg:
    stage: build_nanomsg
    script:
        - "docker build -t build_nanomsg -f BuildNanomsgDockerfile ."
        - "docker tag build_nanomsg $DOCKER_REPO:$DOCKER_PREFIX/build_nanomsg"
        - "docker push $DOCKER_REPO:$DOCKER_PREFIX/build_nanomsg"
variables:
    GIT_SSL_NO_VERIFY: "1"
    DOCKER_REPO: "registry.id.intranet.sky:5001"
    DOCKER_PREFIX: "/id-nft"
    GIT_STRATEGY: clone
