stages:
    - build_nanomsg
    - build_python_nanomsg
    - build_python_msgpack
    - build_python_acurl
    - build_python_ujson
    - build_python_uvloop

build_nanomsg:
    stage: build_nanomsg
    image: docker:17.03.0-ce
    script: 
        - mkdir artifacts
        - docker build -t build_nanomsg -f BuildNanomsgDockerfile .
        - docker run --rm --mount $PWD/artifacts/:/artifacts/ build_nanomsg /bin/true
        - ls $PWD/artifacts
    artifacts:
        when: always
        untracked: true

variables:
    GIT_SSL_NO_VERIFY: "1"
    GIT_STRATEGY: clone
