image: docker:latest

stages:
    - build_nanomsg
    - build_python_nanomsg
    - build_python_msgpack
    - build_python_acurl
    - build_python_ujson
    - build_python_uvloop

services:
    - docker:dind

build_nanomsg:
    stage: build_nanomsg
    script: 
        - mkdir -p /build/$CI_PROJECT_PATH/artifacts 
        - docker build -t build_nanomsg -f BuildNanomsgDockerfile . 
        - docker run --rm -v /build/$CI_PROJECT_PATH/artifacts:/artifacts build_nanomsg
        - cp -R /build/$CI_PROJECT_PATH/artifacts/. artifacts/
    artifacts:
        when: always
        untracked: true

variables:
    DOCKER_DRIVER: overlay2
    GIT_SSL_NO_VERIFY: "1"
    GIT_STRATEGY: clone
