image: docker:latest

stages:
    - build_nanomsg
    - build_python_nanomsg
    - build_python_msgpack
    - build_python_acurl
    - build_python_ujson
    - build_python_uvloop

services:
    - docker:dind

build_nanomsg:
    stage: build_nanomsg
    script: 
        - mkdir -p $CI_PROJECT_DIR/artifacts 
        - docker build -t build_nanomsg -f BuildNanomsgDockerfile . 
        - docker run -t --rm -v $CI_PROJECT_DIR/artifacts:/artifacts build_nanomsg
        - ls $CI_PROJECT_DIR/artifacts
        - cp -R $CI_PROJECT_DIR/artifacts/. artifacts/
        - ls artifacts 
    artifacts:
        when: always
        untracked: true

variables:
    DOCKER_DRIVER: overlay2
    GIT_SSL_NO_VERIFY: "1"
    GIT_STRATEGY: clone
